name: Build Metrics Export Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-metrics-exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.repo_name }}:${{ inputs.version }}
        continue-on-error: true

  post-run:
    needs: build-metrics-exporter
    uses: ./.github/workflows/post-run.yaml
    with:
      pr_number: ${{ inputs.pr_number }}
      repo_name: ${{ inputs.repo_name }}
      version: metrics-alpha-${{ inputs.version }}
      hub_url: https://hub.docker.com/r/${{ inputs.repo_name }}
      result: ${{ needs.build-metrics-exporter.result }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
