name: Build API Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.repo_name }}:api_dev-${{ inputs.version }}
        continue-on-error: true

      - name: Post run
        uses: ./.github/workflows/post-run.yaml
        with:
          pr_number: ${{ inputs.pr_number }}
          repo_name: ${{ inputs.repo_name }}
          version: ${{ inputs.version }}
          hub_url: https://hub.docker.com/repository/docker/ramossrenato/weather_api
          result: ${{ steps.docker_build.conclusion }}
