name: Build/push Orchestrator

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    if: |
      github.event.issue.pull_request != null &&
      github.event.comment.body == 'alpha-release'
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      metrics_exporter: ${{ steps.filter.outputs.metrics_exporter }}

    steps:
      - name: Debug event
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "is_pr=${{ github.event.issue.pull_request != null }}"
          echo "comment=${{ github.event.comment.body }}"
          echo "pr_number=${{ github.event.issue.number }}"

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 0

      - name: Fetch develop branch
        run: git fetch origin develop:refs/remotes/origin/develop

      - name: Create local branch on develop
        run: git checkout -B pr-on-develop origin/develop

      - name: Merge PR head temporarily
        run: git merge --no-commit --no-ff FETCH_HEAD || true

      - name: List all refs
        run: git show-ref

      - name: Show diff with develop
        run: git diff --name-only develop...

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: develop
          initial-fetch-depth: 0
          filters: |
            api:
              - 'docker/Dockerfile'
              - 'app/**'
            metrics_exporter:
              - 'exporter/**'

      - name: Debug filters
        run: |
          echo "api=${{ steps.filter.outputs.api }}"
          echo "metrics_exporter=${{ steps.filter.outputs.metrics_exporter }}"

  build-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    uses: ./.github/workflows/build-api.yaml
    with:
      version: api-alpha-${{ github.event.issue.number }}
      dockerfile: docker/Dockerfile
      repo_name: ramossrenato/dev_weather_api_alpha_release
      pr_number: ${{ github.event.issue.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-metrics-exporter:
    needs: detect-changes
    if: needs.detect-changes.outputs.metrics_exporter == 'true'
    uses: ./.github/workflows/build-metrics-export.yaml
    with:
      version: metrics-alpha-${{ github.event.issue.number }}
      dockerfile: exporter/Dockerfile
      repo_name: ramossrenato/dev_weather_api_alpha_release
      pr_number: ${{ github.event.issue.number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  post-manager:
    needs: [detect-changes, build-api, build-metrics-exporter]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Post no changes comment
        if: needs.detect-changes.outputs.api == 'false' || needs.detect-changes.outputs.metrics_exporter == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ No changes detected in Docker-related files.
            No images were built or pushed.
