name: Build Metrics Export Image

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build-consumer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/metrics-exporter:dev-${{ inputs.sha }}
