name: Python Linters Action

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       github.event.comment.body == 'recheck')
    runs-on: ubuntu-latest

    steps:
      - name: Debug trigger
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "PR? ${{ github.event.issue.pull_request != null }}"
          echo "Comment: ${{ github.event.comment.body || 'N/A' }}"
          echo "Branch: ${{ github.ref_name || github.head_ref }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure Git to use token for private repos
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --locked

      - name: Run black
        run: uv run black --check --diff .

      - name: Run ruff
        working-directory: app
        run: uv run ruff check --fix --exit-non-zero-on-fix

      - name: Run mypy
        run: uv run mypy **/*.py --install-types --non-interactive
