name: Python Linters Action

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Configure Git to use token for private repos
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --locked

      - name: Run black
        run: uv run black --check --diff .

      - name: Run ruff
        working-directory: app
        run: uv run ruff check --fix --exit-non-zero-on-fix

      - name: Run mypy
        run: uv run mypy **/*.py --install-types --non-interactive --verbose
